Implemented registration
StakeGold/sc-nft-amm pull request #4
Opened 2022-12-13 11:01 UTC by vladNed

2022-12-14 10:12 UTC, alexjilavu requested changes

2022-12-14 10:12 UTC, alexjilavu commented on router/src/register.rs
> +        opt_fee_percents: OptionalValue<MultiValue2<u64, u64>>
Will this be of any use? We shall not let the user set his own fee percent amounts, so I would remove this.

2022-12-14 10:12 UTC, alexjilavu commented on router/src/register.rs
> +                require!(value.state == RegistrationState::READY, "This registration is not completed");
I would also allow the state NEW to be rejected. What if the user only pays the fee and does not send the initial liquidity or an error occurs?

2022-12-14 10:12 UTC, alexjilavu commented on router/src/register.rs
> +            None => sc_panic!("Could not find any registration payments")
If we also allow RegistrationState::NEW to be rejected this panic must be removed

2022-12-14 10:12 UTC, alexjilavu commented on router/src/register.rs
> +            ManagedAsyncCallResult::Ok(()) => {
Maybe also transition the registration to a new state like LP_TOKEN_ISSUED here for better traceability?

2022-12-14 10:12 UTC, alexjilavu commented on router/src/register.rs
> +        require!(registration.state == RegistrationState::APPROVED, "This pool registration was not approved yet");
registration.state == RegistrationState::LP_TOKEN_ISSUED

2022-12-15 08:24 UTC, vladNed commented on router/src/register.rs
> +        opt_fee_percents: OptionalValue<MultiValue2<u64, u64>>
removed the optional fees from the endpoint

2022-12-15 08:24 UTC, vladNed commented on router/src/register.rs
> +                require!(value.state == RegistrationState::READY, "This registration is not completed");
made a new status for this

2022-12-15 08:33 UTC, alexjilavu approved these changes

2022-12-15 08:44 UTC, merged